//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pong.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/GMRPongWCF")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Score", Namespace="http://schemas.datacontract.org/2004/07/GMRPongWCF")]
    [System.SerializableAttribute()]
    public partial class Score : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int leftScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rightScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int leftScore {
            get {
                return this.leftScoreField;
            }
            set {
                if ((this.leftScoreField.Equals(value) != true)) {
                    this.leftScoreField = value;
                    this.RaisePropertyChanged("leftScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rightScore {
            get {
                return this.rightScoreField;
            }
            set {
                if ((this.rightScoreField.Equals(value) != true)) {
                    this.rightScoreField = value;
                    this.RaisePropertyChanged("rightScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.IGMRPongService")]
    public interface IGMRPongService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMRPongService/AddGame", ReplyAction="http://tempuri.org/IGMRPongService/AddGameResponse")]
        void AddGame(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMRPongService/getPlayerPosition", ReplyAction="http://tempuri.org/IGMRPongService/getPlayerPositionResponse")]
        Pong.WebService.Position getPlayerPosition(string name, int player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMRPongService/setPlayerPosition", ReplyAction="http://tempuri.org/IGMRPongService/setPlayerPositionResponse")]
        void setPlayerPosition(string name, int player, Pong.WebService.Position position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMRPongService/GetBallPosition", ReplyAction="http://tempuri.org/IGMRPongService/GetBallPositionResponse")]
        Pong.WebService.Position GetBallPosition(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMRPongService/GetScore", ReplyAction="http://tempuri.org/IGMRPongService/GetScoreResponse")]
        Pong.WebService.Score GetScore(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGMRPongService/setScore", ReplyAction="http://tempuri.org/IGMRPongService/setScoreResponse")]
        void setScore(string name, int player, Pong.WebService.Score score);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGMRPongServiceChannel : Pong.WebService.IGMRPongService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GMRPongServiceClient : System.ServiceModel.ClientBase<Pong.WebService.IGMRPongService>, Pong.WebService.IGMRPongService {
        
        public GMRPongServiceClient() {
        }
        
        public GMRPongServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GMRPongServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GMRPongServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GMRPongServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddGame(string name) {
            base.Channel.AddGame(name);
        }
        
        public Pong.WebService.Position getPlayerPosition(string name, int player) {
            return base.Channel.getPlayerPosition(name, player);
        }
        
        public void setPlayerPosition(string name, int player, Pong.WebService.Position position) {
            base.Channel.setPlayerPosition(name, player, position);
        }
        
        public Pong.WebService.Position GetBallPosition(string name) {
            return base.Channel.GetBallPosition(name);
        }
        
        public Pong.WebService.Score GetScore(string name) {
            return base.Channel.GetScore(name);
        }
        
        public void setScore(string name, int player, Pong.WebService.Score score) {
            base.Channel.setScore(name, player, score);
        }
    }
}
